exports.data = [{
  "Large_categories_id": 1,
  "name": "农、林、牧、渔业",
  "industry_lists": [{
    "industry_id": 135,
    "name": "农业"
  }, {
    "industry_id": 136,
    "name": "林业"
  }, {
    "industry_id": 137,
    "name": "畜牧业"
  }, {
    "industry_id": 138,
    "name": "渔业"
  }]
}, {
  "Large_categories_id": 2,
  "name": "采矿业",
  "industry_lists": [{
    "industry_id": 139,
    "name": "煤炭开采和洗选业"
  }, {
    "industry_id": 140,
    "name": "石油和天然气开采业"
  }, {
    "industry_id": 141,
    "name": "黑色金属矿采选业"
  }, {
    "industry_id": 142,
    "name": "有色金属矿采选业"
  }, {
    "industry_id": 143,
    "name": "非金属矿采选业"
  }, {
    "industry_id": 144,
    "name": "其他采矿业"
  }]
}, {
  "Large_categories_id": 3,
  "name": "制造业",
  "industry_lists": [{
    "industry_id": 145,
    "name": "农副食品加工业"
  }, {
    "industry_id": 146,
    "name": "食品制造业"
  }, {
    "industry_id": 147,
    "name": "饮料制造业"
  }, {
    "industry_id": 148,
    "name": "烟草制品业"
  }, {
    "industry_id": 149,
    "name": "纺织业"
  }, {
    "industry_id": 150,
    "name": "纺织服装、鞋、帽制造业"
  }, {
    "industry_id": 151,
    "name": "皮革、毛皮、羽毛(绒)及其制品业"
  }, {
    "industry_id": 152,
    "name": "木材加工及木、竹、藤、棕、草制品业"
  }, {
    "industry_id": 153,
    "name": "家具制造业"
  }, {
    "industry_id": 154,
    "name": "造纸及纸制品业"
  }, {
    "industry_id": 155,
    "name": "印刷业和记录媒介的复制"
  }, {
    "industry_id": 156,
    "name": "文教体育用品制造业"
  }, {
    "industry_id": 157,
    "name": "石油加工、炼焦及核燃料加工业"
  }, {
    "industry_id": 158,
    "name": "化学原料及化学制品制造业"
  }, {
    "industry_id": 159,
    "name": "医药制造业"
  }, {
    "industry_id": 160,
    "name": "化学纤维制造业"
  }, {
    "industry_id": 161,
    "name": "橡胶制品业"
  }, {
    "industry_id": 162,
    "name": "塑料制品业"
  }, {
    "industry_id": 163,
    "name": "非金属矿物制品业"
  }, {
    "industry_id": 164,
    "name": "黑色金属冶炼及压延加工业"
  }, {
    "industry_id": 165,
    "name": "有色金属冶炼及压延加工业"
  }, {
    "industry_id": 166,
    "name": "金属制品业"
  }, {
    "industry_id": 167,
    "name": "通用设备制造业"
  }, {
    "industry_id": 168,
    "name": "专用设备制造业"
  }, {
    "industry_id": 169,
    "name": "交通运输设备制造业"
  }, {
    "industry_id": 170,
    "name": "电气机械及器材制造业"
  }, {
    "industry_id": 171,
    "name": "通信设备、计算机及其他电子设备制造业"
  }, {
    "industry_id": 172,
    "name": "仪器仪表及文化、办公用机械制造业"
  }, {
    "industry_id": 173,
    "name": "工艺品及其他制造业"
  }, {
    "industry_id": 174,
    "name": "废弃资源和废旧材料回收加工业"
  }]
}, {
  "Large_categories_id": 4,
  "name": "电力、煤气及水的生产和供应业",
  "industry_lists": [{
    "industry_id": 175,
    "name": "电力、热力的生产和供应业"
  }, {
    "industry_id": 176,
    "name": "煤气生产和供应业"
  }, {
    "industry_id": 177,
    "name": "水的生产和供应业"
  }]
}, {
  "Large_categories_id": 5,
  "name": "建筑业",
  "industry_lists": [{
    "industry_id": 178,
    "name": "房屋和土木工程建筑业"
  }, {
    "industry_id": 179,
    "name": "建筑安装业"
  }, {
    "industry_id": 180,
    "name": "建筑装饰业"
  }, {
    "industry_id": 181,
    "name": "其他建筑业"
  }]
}, {
  "Large_categories_id": 6,
  "name": "交通运输、仓储及邮政业",
  "industry_lists": [{
    "industry_id": 182,
    "name": "铁路运输业"
  }, {
    "industry_id": 183,
    "name": "道路运输业"
  }, {
    "industry_id": 184,
    "name": "城市公共交通业"
  }, {
    "industry_id": 185,
    "name": "水上运输业"
  }, {
    "industry_id": 186,
    "name": "航空运输业"
  }, {
    "industry_id": 187,
    "name": "管道运输业"
  }, {
    "industry_id": 188,
    "name": "装卸搬运和其他运输服务业"
  }, {
    "industry_id": 189,
    "name": "仓储业"
  }, {
    "industry_id": 190,
    "name": "邮政业"
  }]
}, {
  "Large_categories_id": 7,
  "name": "信息传输、计算机服务和软件业",
  "industry_lists": [{
    "industry_id": 191,
    "name": "电信和其他信息传输服务业"
  }, {
    "industry_id": 192,
    "name": "计算机服务业"
  }, {
    "industry_id": 193,
    "name": "软件业"
  }]
}, {
  "Large_categories_id": 8,
  "name": "批发和零售业",
  "industry_lists": [{
    "industry_id": 194,
    "name": "批发业"
  }, {
    "industry_id": 195,
    "name": "零售业"
  }]
}, {
  "Large_categories_id": 9,
  "name": "住宿和餐饮业",
  "industry_lists": [{
    "industry_id": 196,
    "name": "住宿业"
  }, {
    "industry_id": 197,
    "name": "餐饮业"
  }]
}, {
  "Large_categories_id": 10,
  "name": "金融业",
  "industry_lists": [{
    "industry_id": 198,
    "name": "银行业"
  }, {
    "industry_id": 199,
    "name": "证券业"
  }, {
    "industry_id": 200,
    "name": "保险业"
  }, {
    "industry_id": 201,
    "name": "其他金融活动"
  }]
}, {
  "Large_categories_id": 11,
  "name": "房地产业",
  "industry_lists": [{
    "industry_id": 202,
    "name": "房地产业"
  }]
}, {
  "Large_categories_id": 12,
  "name": "租赁和商务服务业",
  "industry_lists": [{
    "industry_id": 203,
    "name": "租赁业"
  }, {
    "industry_id": 204,
    "name": "商务服务业"
  }]
}, {
  "Large_categories_id": 13,
  "name": "科学研究、技术服务和地质勘查业",
  "industry_lists": [{
    "industry_id": 205,
    "name": "研究与试验发展"
  }, {
    "industry_id": 206,
    "name": "专业技术服务业"
  }, {
    "industry_id": 207,
    "name": "科技交流和推广服务业"
  }, {
    "industry_id": 208,
    "name": "地质勘查业"
  }]
}, {
  "Large_categories_id": 14,
  "name": "水利、环境和公共设施管理业",
  "industry_lists": [{
    "industry_id": 209,
    "name": "水利管理业"
  }, {
    "industry_id": 210,
    "name": "环境管理业"
  }, {
    "industry_id": 211,
    "name": "公共设施管理业"
  }]
}, {
  "Large_categories_id": 15,
  "name": "居民服务和其他服务业",
  "industry_lists": [{
    "industry_id": 212,
    "name": "居民服务业"
  }, {
    "industry_id": 213,
    "name": "其他服务业"
  }]
}, {
  "Large_categories_id": 16,
  "name": "教育",
  "industry_lists": [{
    "industry_id": 214,
    "name": "教育"
  }]
}, {
  "Large_categories_id": 17,
  "name": "卫生、社会保障和社会福利业",
  "industry_lists": [{
    "industry_id": 215,
    "name": "卫生"
  }, {
    "industry_id": 216,
    "name": "社会保障业"
  }, {
    "industry_id": 217,
    "name": "社会福利业"
  }]
}, {
  "Large_categories_id": 18,
  "name": "文化、体育和娱乐业",
  "industry_lists": [{
    "industry_id": 218,
    "name": "新闻出版业"
  }, {
    "industry_id": 219,
    "name": "广播、电视、电影和音像业"
  }, {
    "industry_id": 220,
    "name": "文化艺术业"
  }, {
    "industry_id": 221,
    "name": "体育"
  }, {
    "industry_id": 222,
    "name": "娱乐业"
  }]
}];